### ISSUE TITLE
You're crazy

### ISSUE THREAD

**Issue by atrandafir** [notwaldorf/cat-dns#12]
:-D

**Comment by kutsan** [comment]
[I'm sure she reaaallly loves cats.](https://www.youtube.com/watch?v=sP4NMoJcFd4)

**Comment by colmmacc** [comment]
Maybe you all know each other and it's in good spirits, but this issue reads like either sexist infantilizing (oh how cute!), or desperate negging. 

Personally I found this project a pretty awesome demo of both Node and DNS and have used to help others learn one or another.

**Comment by notwaldorf** [comment]
@colmmacc Thanks Colm. I don't know these folks; just another day on the internet, i guess. 😒

**Comment by kutsan** [comment]
Hey hey hey, wait a minute, what's going on. Sexist, negging; no way. I didn't mean to say like that, that wasn't my intention. I bet OP also didn't mean to say this way. I do found this tutorial very helpful and cute. I just teasing. Don't get wrong. 😓

**Comment by notwaldorf** [comment]
It's fine, y'all. Just opening an issue with no content and a title "You're crazy" isn't very nice, especially if we don't know each other.

**Comment by kutsan** [comment]
@atrandafir You dummy, see what you did.

**Comment by atrandafir** [comment]
I'm sorry! It was a positive "you're crazy" because I was amazed of you building a DNS server that will show you cats!
